# Generated by Django 4.2.4 on 2023-10-23 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=300, verbose_name='Details')),
                ('is_usable', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attribute.brand')),
                ('cloth_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attribute.clothtype')),
                ('colors', models.ManyToManyField(to='attribute.color')),
                ('season', models.ManyToManyField(to='attribute.season')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attribute.size')),
            ],
        ),
    ]
